### ISSUE TITLE
Proper readme

### ISSUE THREAD

**Issue by rahulkrishnan221** [codezoned/BlogCast#2]
Write a proper readme so that one who is unaware how to run can easily refer it.
For writing readme refer to the last commit (description).
Suggestion::::It would be better if you use intellij as ide.
Required:;monodb server on your local pc.

**Comment by ionicc** [comment]
Since I myself have no idea to run the app, Writing a README won't work out. 
First, We have to confirm if it's in a pre alpha stage. Once done, We'll put down a README.
